language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g nyc
script:
  - npm test -- --coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_success: npm run coverage
